<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All' => '',
  'As a reminder, now would be a good time to secure your installation. Details on how to secure your installation can be found {{github}}. I hope you enjoy using CiiMS!' => '',
  'Check MySQL Connection' => '',
  'CiiMS Installer' => '',
  'CiiMS has encountered an error during the installation that requires manual intervention.' => '',
  'CiiMS has finished the installation, you are now ready to login. Click the login button below to login to your site.' => '',
  'CiiMS has successfully been installed!' => '',
  'CiiMS is now installing the database. {{donotleave}} A notification will appear when it\'s OK to continue.' => '',
  'CiiMS was unable to add your user to the database.' => '',
  'Configuration directory is not writable. This must be corrected before your settings can be applied.' => '',
  'Continue' => '',
  'Could Not Complete Migration' => '',
  'Create' => '',
  'Create Admin User' => '',
  'DO NOT LEAVE THIS PAGE UNTIL THE PROCESS HAS COMPLETED.' => '',
  'Database Host' => '',
  'Database Migration in Progress...' => '',
  'Database Name' => '',
  'Display Name' => '',
  'Email' => '',
  'Email Address' => '',
  'Horray!' => '',
  'If you don\'t have a MySQL database setup yet, please do so now, then return to this page.' => '',
  'If you still get stuck, write down everything you did and submit an issue at {{github}}.' => '',
  'Lets setup your first admin user, and set a few site settings. All of these settings can be changed later in the admin panel.' => '',
  'Login' => '',
  'Migration Complete!' => '',
  'Migrations failed to complete. Please correct any errors, and run `php protected/yiic.php migrate up` manually to verify the database is installed.' => '',
  'Oh Snap!' => '',
  'Password' => '',
  'Press the "back" button in your browser to go back to the previous page and try whatever action you last performed again.' => '',
  'Press the button below and let CiiMS figure out what you need to do next.' => '',
  'Site Name' => '',
  'The following error was produced during the installation.' => '',
  'The installer cannot run, because CiiMS is already installed' => '',
  'There was an error saving your details to the database.' => '',
  'Unable to connect to database using the provided credentials.' => '',
  'Username' => '',
  'Warning!' => '',
  'github' => '',
  'on github' => '',
  '{all} Done!' => '',
  '{connect} to MySQL Database' => '',
  '{create} Admin User' => '',
  '{install} and Migrate Database' => '',
  '{woah} An error occured!' => '',
  '{{horray}} The database has been installed. Press the "Continue" button below to create an admin user.' => '',
  '{{ohsnap}} Looks like the database istallations failed. Most likely this is an issue with your database connection. Alternatively, you could try running the migrations from the command line.' => '',
  '{{warning}} {{error}}' => '',
);
